# Generated by Django 5.2.7 on 2026-01-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_product_avaliable_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ascending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.category', verbose_name='categoria ascendente'),
        ),
    ]
