# Generated by Django 5.2.7 on 2025-10-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_product_avaliable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='nan', max_length=20, unique=True, verbose_name='sku'),
            preserve_default=False,
        ),
    ]
