# Generated by Django 5.2.7 on 2026-01-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avaliable',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço'),
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50, verbose_name='tipo de mudança')),
                ('quantity_changed', models.IntegerField(verbose_name='quantidade alterada')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'Registro de Inventário',
                'verbose_name_plural': 'Registros de Inventário',
            },
        ),
    ]
