# Generated by Django 5.2.7 on 2026-01-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_category_ascending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryLog',
        ),
    ]
