# Generated by Django 6.0.3 on 2026-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
