# Generated by Django 5.1.4 on 2025-04-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_product_options_product_photo_delete_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avaliable',
            field=models.BooleanField(default=True, verbose_name='disponível'),
        ),
    ]
