# Generated by Django 6.0.1 on 2026-03-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_delete_inventorylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ascending',
        ),
    ]
